"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var linked_list_1 = require("./linked-list");
exports.LinkedList = linked_list_1.LinkedList;
var queue_1 = require("./queue");
exports.Queue = queue_1.Queue;
var deque_1 = require("./deque");
exports.Deque = deque_1.Deque;
var stack_1 = require("./stack");
exports.Stack = stack_1.Stack;
var structure_1 = require("./structure");
exports.Structure = structure_1.Structure;
